### ISSUE TITLE
代码理解

### ISSUE THREAD

**Issue by shenhaibo123** [neural-lab/ASF-BP#1]
作者你好！
计算梯度的时候为什么要用input>output做个筛选呢
def ave(output, input):
    c = input >= output
    if input[c].sum() < 1e-3:
        return 1
    return output[c].sum()/input[c].sum()

**Comment by neural-lab** [comment]
我们认为准确的scale factor应该是满足输入大于输出的(阈值为1时），但是由于负值输入的存在可能会导致输入小于输出，所以我们仅考虑输入大于输出的项来计算scale factor
